### ISSUE TITLE
about ICA codes for HCP Behaviours Data

### ISSUE THREAD

**Issue by sunlianglong** [yetianmed/subcortex#3]
Hi!
It's a very nice work! There are many places to learn and use for reference! In the process of reading the paper carefully, I have a strong interest in the ICA part. I was going to repeat the behavior data dimensionality reduction myself, but it turns out that this part of the work is also very heavy, you do it very detailed, with a lot of verification and thinking. So I would like to ask, can the ICA part of the code be open source? Or behavior data after dimensionality reduction ? (I have reasonably applied for restricted HCP  behaviour data)
 
Best, 
Lianglong Sun

**Comment by yetianmed** [comment]
Hi Lianglong, thanks for your interest. 

I would be happy to share the code. However, due to participant data access restrictions imposed by the HCP, the individual weights for the behavioral dimensions cannot be made publicly available. Happy to discuss further regarding data sharing if you contact me via email: ye.tian2@unimelb.edu.au

Cheers,
Ye
